### ISSUE TITLE
上下左右滑动如果能有物理加速会更完美

### ISSUE THREAD

**Issue by jozhi** [MeCKodo/eTouch#2]
如果能有带物理加速的版本就好了，项目中要做类似的功能以及转盘。其实两种都算是 touch 的高级应用，也有老兄实现了，但是不太好用。

**Comment by MeCKodo** [comment]
哥，坐标位移啥得都有你不是能自己实现吗。。哪怕CSS3都可以实现转盘啊缓动曲线啊，不要这么死板嘛

**Comment by jozhi** [comment]
先入为主的进行批判，差评。

以下是选项卡滑动的实例：http://ustbhuangyi.github.io/picker/
另外转盘也不是你想的那个样子，几个选项只是填充了半圆，所以并不是完全转盘。
